# Generated by Django 5.2.8 on 2025-12-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0013_flightoffermodel_offer_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=40, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_option', models.CharField(default='STANDARD', max_length=20)),
                ('final_price_inr', models.FloatField()),
                ('booking_status', models.CharField(default='PENDING', max_length=20)),
                ('pnr', models.CharField(blank=True, max_length=30, null=True)),
                ('booking_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.flightoffermodel')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_flight.travelerdetail')),
            ],
        ),
    ]
