# Generated by Django 5.2.8 on 2025-12-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelerdetail',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
