# Generated by Django 5.2.8 on 2025-12-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_flight', '0002_rename_phone_no_travelerdetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingmodel',
            name='extras_amount_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='selected_extras',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
