# Generated by Django 5.2.8 on 2026-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_flight', '0003_flightbookingmodel_extras_amount_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingmodel',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='razorpay_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
