# Generated by Django 5.2.8 on 2026-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_flight', '0004_flightbookingmodel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbookingmodel',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='flightbookingmodel',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='flightbookingmodel',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='payu_mihpayid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='payu_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='payu_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingmodel',
            name='payu_txnid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
