# Generated by Django 5.2.8 on 2026-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_flight', '0005_remove_flightbookingmodel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingmodel',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
