# Generated by Django 5.2.8 on 2026-04-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_flight', '0006_flightbookingmodel_payment_verified'),
        ('routes', '0013_flightoffermodel_offer_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('FAILED', 'Failed')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='extras_amount_inr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='fare_option',
            field=models.CharField(blank=True, default='STANDARD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='final_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='flight_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.flightoffermodel'),
        ),
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='payu_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingmodel',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_flight.travelerdetail'),
        ),
    ]
