# Generated by Django 5.2.7 on 2025-10-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCountryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('airport_country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('airport_region_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportCityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('iataCode', models.CharField(blank=True, max_length=6, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='routes.airportcountrydetail')),
            ],
        ),
        migrations.CreateModel(
            name='AirportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='routes.airportcitydetail')),
            ],
        ),
        migrations.CreateModel(
            name='AirportTimeZoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.CharField(blank=True, max_length=6, null=True)),
                ('reference_local_datetime', models.DateTimeField(blank=True, null=True)),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timezone', to='routes.airportdetail')),
            ],
        ),
    ]
