# Generated by Django 5.2.7 on 2025-10-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportcitydetail',
            name='country',
        ),
        migrations.RemoveField(
            model_name='airportdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='airporttimezonemodel',
            name='airport',
        ),
        migrations.DeleteModel(
            name='AirportCountryDetail',
        ),
        migrations.DeleteModel(
            name='AirportCityDetail',
        ),
        migrations.DeleteModel(
            name='AirportDetail',
        ),
        migrations.DeleteModel(
            name='AirportTimeZoneModel',
        ),
    ]
