# Generated by Django 5.2.7 on 2025-10-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_remove_airportcitydetail_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('airline_code', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price_total', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('stops', models.IntegerField(default=0)),
            ],
        ),
    ]
