# Generated by Django 5.2.7 on 2025-10-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffermodel',
            name='itinerary_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
