# Generated by Django 5.2.7 on 2025-10-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_flightoffermodel_itinerary_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='itinerary_group',
        ),
    ]
