# Generated by Django 5.2.7 on 2025-10-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_remove_flightoffermodel_itinerary_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffermodel',
            name='route_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
