# Generated by Django 5.2.8 on 2025-11-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0006_delete_flightoffermodel'),
        ('routes', '0006_flightoffermodel_route_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='airline_code',
        ),
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='flight_number',
        ),
        migrations.AlterField(
            model_name='flightoffermodel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_destination', to='airports.airportmodel'),
        ),
        migrations.AlterField(
            model_name='flightoffermodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_origin', to='airports.airportmodel'),
        ),
        migrations.AlterField(
            model_name='flightoffermodel',
            name='route_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_offers', to='routes.routepathmodel'),
        ),
        migrations.CreateModel(
            name='RoutesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=10)),
                ('airline_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_number', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='airports.airportmodel')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origin', to='airports.airportmodel')),
                ('route_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.routepathmodel')),
            ],
        ),
    ]
