# Generated by Django 5.2.8 on 2025-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_routepathmodel_remove_flightoffermodel_airline_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffermodel',
            name='amadeus_offer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
