# Generated by Django 5.2.8 on 2025-11-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_flightoffermodel_amadeus_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightoffermodel',
            old_name='amadeus_offer',
            new_name='offer_json',
        ),
    ]
