# Generated by Django 5.2.8 on 2025-11-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_rename_amadeus_offer_flightoffermodel_offer_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='offer_json',
        ),
    ]
