# Generated by Django 5.2.8 on 2025-11-07 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_remove_flightoffermodel_offer_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepathmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
