# Generated by Django 5.2.8 on 2025-11-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_routepathmodel_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepathmodel',
            name='uuid',
        ),
    ]
