# Generated by Django 5.2.8 on 2025-11-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_remove_routepathmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffermodel',
            name='offer_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
