# Generated by Django 5.2.8 on 2026-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_flightoffermodel_offer_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffermodel',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
