# Generated by Django 5.2.8 on 2026-04-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_flightoffermodel_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightoffermodel',
            name='departure_date',
        ),
    ]
