# Generated by Django 5.2.8 on 2026-04-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_remove_flightoffermodel_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffermodel',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
