# Generated by Django 5.2.7 on 2025-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
