# Generated by Django 5.2.7 on 2025-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
