# Generated by Django 5.2.7 on 2025-10-27 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_delete_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportmodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='airports.citymodel'),
        ),
    ]
