# Generated by Django 5.2.7 on 2025-10-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0005_flightoffermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightOfferModel',
        ),
    ]
