# Generated by Django 5.2.8 on 2025-11-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0006_delete_flightoffermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='airports.countrymodel'),
        ),
    ]
