# Generated by Django 5.2.8 on 2025-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0007_alter_citymodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='iataCode',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='airportmodel',
            unique_together={('name', 'city')},
        ),
    ]
