# Generated by Django 5.2.8 on 2025-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0008_alter_citymodel_iatacode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airportmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='iataCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
